on:
  # Manually trigger this workflow, using the code from a particular PR
  workflow_dispatch:
    inputs:
      pr_id:
        required: false
        description: Test the contents of this Pull Request

permissions: read-all

jobs:
  scikit-learn:
    runs-on: ubuntu-latest
    name: Test scikit-learn
    permissions:
      pull-requests: write
      issues: write
    defaults:
      run:
        # Needed so that automatically activiating the `test` conda env works
        shell: bash -el {0}
    steps:
      - run: |
          env
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Checkout main repository
        uses: actions/checkout@v2
      - name: Checkout a particular Pull Request
        if: inputs.pr_id
        env:
          PR_ID: ${{ inputs.pr_id }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Checking out Pull Request" ${{ env.PR_ID }}
          gh pr checkout ${{ env.PR_ID }}
      - name: Store commit SHA
        id: commit-sha
        run: |
          echo SHA=$(git rev-parse HEAD) >> "$GITHUB_OUTPUT"
      - name: List repo contents
        id: tests
        run: |
          ls -hals *
          echo ===============
          git log -1
      - name: conda, conda, conda
        run: |
          conda list
          echo =======
          conda info
      - name: Create or update PR comment
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ inputs.pr_id }}
          RUN_ID: ${{ github.run_id }}
          BRANCH_SHA: ${{ steps.commit-sha.outputs.SHA }}
          WORKFLOW_STATUS: ${{ steps.tests.outcome }}
        run: |
          env
