on:
  pull_request:
    types:
      - labeled

#permissions: read-all

jobs:
  scikit-learn:
    if: contains(github.event.pull_request.labels.*.name, 'CUDA CI')
    runs-on: ubuntu-latest
    name: Test scikit-learn
    defaults:
      run:
        # Needed so that automatically activiating the `test` conda env works
        shell: bash -el {0}
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: CUDA CI
      - run: |
          env
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Checkout main repository
        uses: actions/checkout@v2
      - name: List repo contents
        id: tests
        run: |
          ls -hals *
          echo ===============
          git log -1
      - name: conda, conda, conda
        run: |
          conda list
          echo =======
          conda info
