on:
  pull_request:

permissions: read-all

jobs:
  scikit-learn:
    runs-on: ubuntu-latest
    environment: CUDA CI
    name: Test scikit-learn
    permissions:
      pull-requests: write
      issues: write
      statuses: write
    defaults:
      run:
        # Needed so that automatically activiating the `test` conda env works
        shell: bash -el {0}
    steps:
      - run: |
          env
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Checkout main repository
        uses: actions/checkout@v2
      - name: Store commit SHA
        id: commit-sha
        run: |
          echo SHA=$(git rev-parse HEAD) >> "$GITHUB_OUTPUT"
      - name: List repo contents
        id: tests
        run: |
          ls -hals *
          echo ===============
          git log -1
      - name: conda, conda, conda
        run: |
          conda list
          echo =======
          conda info
      - name: Create or update PR comment
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          RUN_ID: ${{ github.run_id }}
          BRANCH_SHA: ${{ steps.commit-sha.outputs.SHA }}
          WORKFLOW_STATUS: ${{ steps.tests.outcome }}
        run: |
          python -m pip install requests
          python ./cuda_ci_status.py
