on:
  # Manually trigger this workflow, using the code from a particular PR
  workflow_dispatch:
    inputs:
      pr_id:
        required: true
        description: Test the contents of this Pull Request

permissions: read-all

jobs:
  scikit-learn:
    runs-on: ubuntu-latest
    name: Test scikit-learn
    defaults:
      run:
        # Needed so that automatically activiating the `test` conda env works
        shell: bash -el {0}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Checkout main repository
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          activate-environment: test
          environment-file: pylatest_conda_forge_mkl_array-api_linux-64_conda.lock
      - name: Cache conda env
        id: cache-conda
        uses: actions/cache@v3
        env:
          cache-name: cache-conda-env
        with:
          path: /usr/share/miniconda
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pylatest_conda_forge_mkl_array-api_linux-64_conda.lock') }}
      - name: Checkout a particular Pull Request
        if: inputs.pr_id
        env:
          PR_ID: ${{ inputs.pr_id }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Checking out Pull Request" ${{ env.PR_ID }}
          gh pr checkout ${{ env.PR_ID }}
      - name: List repo contents
        run: |
          ls -hals *
          echo ===============
          git log -1
      - name: conda, conda, conda
        run: |
          conda list
          echo =======
          conda info
