on:
  workflow_dispatch:

jobs:
  scikit-learn:
    runs-on: ubuntu-latest
    name: Test scikit-learn
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          source $CONDA/bin/activate
          conda install -n base conda conda-libmamba-solver -y
          conda config --set solver libmamba
          conda install -c conda-forge "numpy" -y
          python --version
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: scikit-learn/scikit-learn
      - name: Configure git
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "noreply@myemail.com"
          git remote add upstream https://github.com/my-user/myapp.git
        shell: bash
